name: Trigger auto deployment for myblazorwasmcontainer

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/myblazorwasmcontainer-AutoDeployTrigger-204f23d5-a722-4b9b-80be-90da3cdb3a2b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: mychosencontainerregistry.azurecr.io
          username: ${{ secrets.MYBLAZORWASMCONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.MYBLAZORWASMCONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mychosencontainerregistry.azurecr.io/myblazorwasmcontainer:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYBLAZORWASMCONTAINER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n myblazorwasmcontainer -g resource1 --server mychosencontainerregistry.azurecr.io --username  ${{ secrets.MYBLAZORWASMCONTAINER_REGISTRY_USERNAME }} --password ${{ secrets.MYBLAZORWASMCONTAINER_REGISTRY_PASSWORD }}
            az containerapp update -n myblazorwasmcontainer -g resource1 --image mychosencontainerregistry.azurecr.io/myblazorwasmcontainer:${{ github.sha }}
